site_name: Artware Help Docs
nav:
    - Home: index.md
    - Localis365:
        - Core:
            - Maestros: 
                - Configuración General: 'ConfiguracionGeneralLATAM.md'
                - Clientes: 'Clientes.md'
                - Tipo Contribuyente: 'TipoContribuyente.md'
                - Tipo Clase Comprobante: 'TipoClaseComprobante.md'
                - Proveedores: 'Proveedores.md'
                - Letra Clase Comprobante: 'LetraClaseComprobante.md'
                - Grupo Tipo Cuenta: 'GrupoTipoCuenta.md'
                - Clase Comprobante: 'ClaseComprobante.md'
        - Localización Argentina:
            - Aplicativo Ganancias Sociedades : 'AplicativoGananciasSociedades.md'
            - Aplicativo SICORE : 'AplicativoSICORE.md'
            - Aplicativo SIFERE : 'AplicativoSIFERE.md'
            - IVA SIAP: 'aplica tivos/IVASIAP.md'
        - Localización Perú:
            - Asiento Por Naturaleza y Destino: 'AsientoPorNaturalezaDestino.md'
            - diagrams: 'diagrams.md'
    - Ajuste por inflación:
        - Configuración General: 'AjustePorInflacion/ConfiguracionGeneral.md'
        - Indices de Ajuste por Inflación: 'AjustePorInflacion/IndicesDeAjustePorInflacion.md'
        - Proceso de Ajuste: 'AjustePorInflacion/ProcesoDeAjuste.md'
        - Validación de Fechas: 'AjustePorInflacion/ValidacionDeFechas.md'
        - Presupuesto contable: 'AjustePorInflacion/Presupuesto.md'
        - Asientos contables: 'AjustePorInflacion/Asiento.md'
        - Saldos Iniciales: 'AjustePorInflacion/SaldosIniciales.md'
theme:
    name: 'material'
    navigation_depth: '3'
    logo: img/logo.png

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

    