site_name: Artware LATAM Localization Help
nav:
    - Home: index.md
    - Core:
        - Maestros: 
            - Configuración General: 'ConfiguracionGeneralLATAM.md'
            - Clientes: 'Clientes.md'
            - Tipo Contribuyente: 'TipoContribuyente.md'
            - Tipo Clase Comprobante: 'TipoClaseComprobante.md'
            - Proveedores: 'Proveedores.md'
            - Letra Clase Comprobante: 'LetraClaseComprobante.md'
            - Grupo Tipo Cuenta: 'GrupoTipoCuenta.md'
            - Clase Comprobante: 'ClaseComprobante.md'
    - Localización Argentina:
        - Aplicativo Ganancias Sociedades : 'AplicativoGananciasSociedades.md'
        - Aplicativo SICORE : 'AplicativoSICORE.md'
        - Aplicativo SIFERE : 'AplicativoSIFERE.md'
    - Localización Perú:
        - Asiento Por Naturaleza y Destino: 'AsientoPorNaturalezaDestino.md'
        
theme:
    name: 'material'
    navigation_depth: '3'
    logo: img/logo.png

    